version: "3"
services:
  iota-admin:
    environment:
      - APP_ENV=development
      - COOKIE_SECRET=d60285f2976fa1f7e5fb654ea4c774d6fbb7482f2fe116bf38c53307e6587e51
      - LOG_LEVEL=DEBUG
      - BYPASS_AUTH=false
      - TZ:"Europe/Berlin"
      - USERNAME=fbuedding
      - PASSWORD=test
    build:
      dockerfile: dev.Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
    - 8080:8080  
  iot-agent:
    image: fiware/iotagent-ul:latest
    hostname: iot-agent
    depends_on:
        - mongodb
    expose:
        - "4061"
        - "7896"
    ports:
        - "4061:4061"
        - "7896:7896"
    environment:
        - "IOTA_CB_HOST=orion"
        - "IOTA_CB_PORT=1026"
        - "IOTA_NORTH_PORT=4061"
        - "IOTA_REGISTRY_TYPE=mongodb"
        - "IOTA_MONGO_HOST=mongodb"
        - "IOTA_MONGO_PORT=27017"
        - "IOTA_MONGO_DB=iotagent-ul"
        - "IOTA_HTTP_PORT=7896"
        - "IOTA_PROVIDER_URL=http://iot-agent:4061"
        - "IOTA_MQTT_HOST=mosquitto"
        - "IOTA_MQTT_PORT=1883"
  iota-weatherstations:
    image: scilabsbo/iotagent-http-query:latest
    depends_on:
      - mongodb
    environment:
      - TZ=Europe/Berlin
      - HTTP_SOUTH_HOST=0.0.0.0
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent-wunderground
      - IOTA_PROVIDER_URL=http://iota-weatherstations:4041
      - IOTA_LOG_LEVEL=DEBUG
  mongodb:
    image: mongo
    hostname: mongodb
    ports:
        - "27017:27017"
    command: --bind_ip_all 
  orion:
    image: fiware/orion
    hostname: orion
    depends_on:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
        - default
    expose:
        - '1883'
        - '9001'
    ports:
        - '1883:1883'
        - '9001:9001'
    volumes:
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

 
