// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.639
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func LoginForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label class=\"form-control\"><div class=\"label\"><span class=\"label-text font-bold\">Login:</span></div><div class=\"flex flex-row justify-center\"><form hx-post=\"auth/login\" hx-target=\"closest label\" hx-indicator=\"#loading\" class=\"join\"><input type=\"text\" name=\"username\" placeholder=\"username\" autocomplete=\"username\" id=\"username\" required class=\"input input-bordered w-full max-w-xs join-item\"> <input type=\"password\" name=\"password\" placeholder=\"password\" autocomplete=\"current-password\" id=\"current-password\" required class=\"input input-bordered w-full max-w-xs join-item\"> <button type=\"submit\" class=\"btn btn-primary join-item\">Login <span class=\"loading loading-spinner loading-lg htmx-indicator\" id=\"loading\"></span></button></form></div></label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
